interface menuProps {
  nome: string
  nameSection: string | null
  id: number
  valor: string
  imageSrc: string
}

export const dishes: menuProps[] = [
  {
    nome: 'Virado à Paulista - Segunda-feira',
    nameSection: 'Pratos do dia',
    id: 1,
    valor: 'A partir de: R$ 24,90',
    imageSrc: '/assets/Virado_a_Paulista_1.jpg',
  },
  {
    nome: 'Bife à rolê - Terça-feira',
    nameSection: null,
    id: 2,
    valor: 'A partir de: R$ 24,90',
    imageSrc: '/assets/bife_a_role.jpg',
  },
  {
    nome: 'Feijoada - Quarta-feira',
    nameSection: null,
    id: 3,
    valor: 'A partir de: R$ 24,90',
    imageSrc: '/assets/feijoada.jpg',
  },
  {
    nome: 'Macarrão com frango - Quinta-feira',
    nameSection: null,
    id: 4,
    valor: 'A partir de: R$ 24,90',
    imageSrc: '/assets/macarronada-coxa-sobrecoxa-frango 1.jpg',
  },
  {
    nome: 'Filé de peixe - Sexta-feira',
    nameSection: null,
    id: 5,
    valor: 'A partir de: R$ 24,90',
    imageSrc: '/assets/file_de_peixe.jpg',
  },
  {
    nome: 'Feijoada - Sábado',
    nameSection: null,
    id: 6,
    valor: 'A partir de: R$ 24,90',
    imageSrc: '/assets/feijoada.jpg',
  },
  {
    nome: 'Omelete',
    nameSection: 'Pratos executivos',
    id: 7,
    valor: 'A partir de: R$ 24,90',
    imageSrc: '/assets/omelete.jpg',
  },
  {
    nome: 'Picadinho',
    nameSection: null,
    id: 8,
    valor: 'A partir de: R$ 24,90',
    imageSrc: '/assets/picadinho.jpg',
  },
  {
    nome: 'Fígado Acebolado',
    nameSection: null,
    id: 9,
    valor: 'A partir de: R$ 24,90',
    imageSrc: '/assets/figado_acebolado.jpg',
  },
  {
    nome: 'Frango ao Molho',
    nameSection: null,
    id: 10,
    valor: 'A partir de: R$ 24,90',
    imageSrc: '/assets/frango_ao_molho.png',
  },
  {
    nome: 'Costela ao Molho',
    nameSection: null,
    id: 11,
    valor: 'A partir de: R$ 24,90',
    imageSrc: '/assets/costela_ao_molho.png',
  },
  {
    nome: 'Calabresa',
    nameSection: null,
    id: 12,
    valor: 'A partir de: R$ 24,90',
    imageSrc: '/assets/calabresa.png',
  },
  {
    nome: 'Bife Acebolado',
    nameSection: null,
    id: 13,
    valor: 'A partir de: R$ 24,90',
    imageSrc: '/assets/bife_acebolado.png',
  },
  {
    nome: 'Bife à Milanesa',
    nameSection: null,
    id: 14,
    valor: 'A partir de: R$ 24,90',
    imageSrc: '/assets/bife_a_milanesa.jpg',
  },
  {
    nome: 'Bife à Cavalo',
    nameSection: null,
    id: 15,
    valor: 'A partir de: R$ 24,90',
    imageSrc: '/assets/bife_a_cavalo.jpg',
  },
  {
    nome: 'Frango à Passarinho',
    nameSection: null,
    id: 16,
    valor: 'A partir de: R$ 24,90',
    imageSrc: '/assets/frango_a_passarinho.jpg',
  },
  {
    nome: 'Picanha',
    nameSection: 'Pratos especiais',
    id: 17,
    valor: 'A partir de: R$ 35,00',
    imageSrc: '/assets/picanha.jpg',
  },
  {
    nome: 'Filé Mignon',
    nameSection: null,
    id: 18,
    valor: 'A partir de: R$ 32,00',
    imageSrc: '/assets/file_mignon.jpg',
  },
  {
    nome: 'Contra Filé',
    nameSection: null,
    id: 19,
    valor: 'A partir de: R$ 32,00',
    imageSrc: '/assets/contra_file.jpg',
  },
  {
    nome: 'Parmegiana',
    nameSection: null,
    id: 20,
    valor: 'A partir de: R$ 35,00',
    imageSrc: '/assets/parmegiana.jpg',
  },
  {
    nome: 'Strogonoff',
    nameSection: null,
    id: 21,
    valor: 'A partir de: R$ 35,00',
    imageSrc: '/assets/strogonoff.png',
  },
  {
    nome: 'Filé de Frango Grelhado',
    nameSection: null,
    id: 22,
    valor: 'A partir de: R$ 32,00',
    imageSrc: '/assets/file_de_frango_grelhado.png',
  },
  {
    nome: 'Filé de Frango à Milanesa',
    nameSection: null,
    id: 23,
    valor: 'A partir de: R$ 35,00',
    imageSrc: '/assets/file_de_frango_a_milanesa.png',
  },
  {
    nome: 'Carne Assada c/ Molho Madero',
    nameSection: null,
    id: 24,
    valor: 'A partir de: R$ 35,00',
    imageSrc: '/assets/carne_assada_C_molho_madeira.png',
  },
  {
    nome: 'X-Salada',
    nameSection: 'Hambúrgueres & Beirutes',
    id: 25,
    valor: 'A partir de: R$ 12,00',
    imageSrc: '/assets/x_salada.png',
  },
  {
    nome: 'X-Tudo',
    nameSection: null,
    id: 26,
    valor: 'A partir de: R$ 12,00',
    imageSrc: '/assets/x_tudo.png',
  },
  {
    nome: 'X-Bacon',
    nameSection: null,
    id: 27,
    valor: 'A partir de: R$ 12,00',
    imageSrc: '/assets/x-bacon.png',
  },
  {
    nome: 'X-Filé de Frango',
    nameSection: null,
    id: 28,
    valor: 'A partir de: R$ 12,00',
    imageSrc: '/assets/x-frango.png',
  },
  {
    nome: 'X-Churrasco',
    nameSection: null,
    id: 29,
    valor: 'A partir de: R$ 12,00',
    imageSrc: '/assets/x-churrasco.png',
  },
  {
    nome: 'Americano',
    nameSection: null,
    id: 30,
    valor: 'A partir de: R$ 12,00',
    imageSrc: '/assets/americano.png',
  },
  {
    nome: 'Misto-Quente',
    nameSection: null,
    id: 31,
    valor: 'A partir de: R$ 8,00',
    imageSrc: '/assets/misto-quente.png',
  },
  {
    nome: 'Queijo Quente',
    nameSection: null,
    id: 32,
    valor: 'A partir de: R$ 12,00',
    imageSrc: '/assets/queijo-quente.png',
  },
  {
    nome: 'Beirute',
    nameSection: null,
    id: 33,
    valor: 'A partir de: R$ 12,00',
    imageSrc: '/assets/beirute.png',
  },
  {
    nome: 'Suco de Limão',
    nameSection: 'Bebidas',
    id: 34,
    valor: 'A partir de: R$ 9,00',
    imageSrc: '/assets/suco_de_limao.png',
  },
  {
    nome: 'Água',
    nameSection: null,
    id: 35,
    valor: 'A partir de: R$ 2,00',
    imageSrc: '/assets/agua.png',
  },
  {
    nome: 'Suco Del Valle',
    nameSection: null,
    id: 36,
    valor: 'A partir de: R$ 5,00',
    imageSrc: '/assets/suco_del_valle.png',
  },
  {
    nome: 'Refrigerante - Lata',
    nameSection: null,
    id: 37,
    valor: 'A partir de: R$ 5,00',
    imageSrc: '/assets/refrigerante_lata.png',
  },
  {
    nome: 'Refrigerante - Garrafa 2L',
    nameSection: null,
    id: 38,
    valor: 'A partir de: R$ 12,00',
    imageSrc: '/assets/refrigerante_2l.png',
  },
  {
    nome: 'Refrigerante - Garrafa 600ml',
    nameSection: null,
    id: 39,
    valor: 'A partir de: R$ 8,00',
    imageSrc: '/assets/refrigerante_600ml.png',
  },
  {
    nome: 'Cerveja - Lata',
    nameSection: null,
    id: 40,
    valor: 'A partir de: R$ 6,00',
    imageSrc: '/assets/cerveja_lata.png',
  },
  {
    nome: 'Cerveja - Garrafa 1L',
    nameSection: null,
    id: 41,
    valor: 'A partir de: R$ 14,00',
    imageSrc: '/assets/cerveja_1l.png',
  },
  {
    nome: 'Cerveja - Garrafa 600ml',
    nameSection: null,
    id: 42,
    valor: 'A partir de: R$ 14,00',
    imageSrc: '/assets/cerveja_600ml.png',
  },
  {
    nome: 'Suco de Laranja',
    nameSection: null,
    id: 43,
    valor: 'A partir de: R$ 9,00',
    imageSrc: '/assets/suco_de_laranja.png',
  },
  {
    nome: 'Suco de Maracujá',
    nameSection: null,
    id: 44,
    valor: 'A partir de: R$ 9,00',
    imageSrc: '/assets/suco_de_maracuja.png',
  },
  {
    nome: 'Suco de Abacaxi',
    nameSection: null,
    id: 45,
    valor: 'A partir de: R$ 9,00',
    imageSrc: '/assets/suco_de_abacaxi.png',
  },
  {
    nome: 'Caipirinha',
    nameSection: null,
    id: 46,
    valor: 'A partir de: R$ 17,00',
    imageSrc: '/assets/caipirinha.png',
  },
  {
    nome: 'Cachaça',
    nameSection: null,
    id: 47,
    valor: 'A partir de: R$ 5,00',
    imageSrc: '/assets/cachaça.png',
  },
  {
    nome: 'Whisky',
    nameSection: null,
    id: 48,
    valor: 'A partir de: R$ 12,00',
    imageSrc: '/assets/whisky.png',
  },
]
